name: Build and deploy Python app to Azure Web App - myAIBotAppService

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create & populate virtualenv (named “antenv”)
        run: |
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          deactivate

      - name: Zip app + venv for Run-From-Package
        run: |
          zip -r release.zip . \
            -x ".git/*" ".github/*" "__pycache__/*" "*.pyc" "*.pyo" ".DS_Store"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6B03F930AFAF4B1D96FABDE33BB5A168 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2FB6A7F7C85F434DB4EEC35FEA1EE4EB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A243F752CDFD4CDDA5B3E0A5680AE856 }}
    
      - name: Configure Run-From-Package & disable SCM build
        run: |
          az webapp config appsettings set \
            --resource-group DefaultResourceGroup-WEU \
            --name myAIBotAppService \
            --settings WEBSITE_RUN_FROM_PACKAGE=1 \
                       SCM_DO_BUILD_DURING_DEPLOYMENT=false

      - name: Wait for SCM container restart
        run: sleep 30

      - name: Deploy via Zip
        uses: azure/webapps-deploy@v3
        with:
          app-name: myAIBotAppService
          package: release.zip
